consul:
  ports:
  - 8500:8500/tcp
  command:
  - -server
  - -bootstrap
  - -ui-dir
  - /ui
  image: progrium/consul:latest
registrator:
  command:
  - -internal
  - consul://172.17.0.1:8500
  image: gliderlabs/registrator:latest
  volumes:
  - /var/run/docker.sock:/tmp/docker.sock
haproxy:
  image: asteris/haproxy-consul
  net: host
  environment:
   - HAPROXY_DOMAIN=achappaz.fr
   - CONSUL_CONNECT=172.17.0.1:8500
