version: "2"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    volumes:
     - ./vhost.d/:/etc/nginx/vhost.d
     - ./certs:/etc/nginx/certs:ro
     - ./conf.d:/etc/nginx/conf.d
     - /usr/share/nginx/html
     - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
     - 80:80
     - 443:443
    network_mode: bridge
  nginx-ssl-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - ./certs:/etc/nginx/certs:rw
    volumes_from:
     - nginx-proxy
    network_mode: bridge
