version: '3.4'
services:
  traefik:
    image: traefik
    ports:
      - "8080:8080"
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --docker
      - --docker.swarmmode
      - --docker.domain=traefik
      - --docker.watch
      - --api
  consul:
    image: consul:1.0.6
    command: agent -dev -client 0.0.0.0 -ui
    ports:
      - "8500:8500"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - SERVICE_IGNORE=true
    deploy:
      labels:
        - traefik.port=8500
  registrator:
    image: gliderlabs/registrator:master
    command:
      - -internal
      - -retry-attempts=-1
      - -resync=5
      - -cleanup
      - consul://consul:8500
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    depends_on:
      - consul
  zookeeper:
    image: alexinthesky/zookeeper
    build:
      context: ./
      dockerfile: Dockerfile.zookeeper
    environment:
      - CONSUL_HOST=consul
      - CLUSTER_ID=MYCLUSTER
      - SERVICE_2181_NAME=zookeeper-MYCLUSTER
      - SERVICE_2888_IGNORE=true
      - SERVICE_3888_IGNORE=true
      - SWARM=true
    depends_on:
      - consul
    deploy:
      replicas: 3
  nifi_node:
    image: alexinthesky/nifi
    build:
      context: ./
      dockerfile: Dockerfile.nifi
    environment:
      - CONSUL_CONNECT=consul:8500
      - IS_CLUSTER_NODE="1"
      - SERVICE_IGNORE=true
    deploy:
      replicas: 3
      labels:
        - traefik.port=8080
