#!/bin/bash -ex
BASEDIR=$(readlink -f $(dirname $0))
CLUSTER_ID=${CLUSTER_ID:-MYCLUSTER}
SERVICE_NAME=${SERVICE_2181_NAME:-$CLUSTER_ID-zk}
CONTAINER_IP=$(ip address show eth0|grep inet| sed "s/^.*inet \([^/]\+\).*/\1/")

if [ -z "$SWARM" ]; then
    GETCONTAINERID="/get-container-id.sh"
else
    GETCONTAINERID="/get-container-id_swarm.sh"
fi

if [ -z "$CLUSTER_ID" ]; then
    echo "CLUSTER_ID is not set" >&2
    exit 1
fi

cat > /conf/zoo.cfg.tmpl <<EOF
tickTime=2000
dataDir=/data
clientPort=2181
initLimit=5
syncLimit=2

{{range service "$SERVICE_NAME|any"}}
server.{{plugin "$GETCONTAINERID" .ID}}={{.Address}}:2888:3888
{{end}}

EOF

cat > /conf/myid.tmpl <<EOF
{{range service "$SERVICE_NAME|any"}}{{if  eq .Address "$CONTAINER_IP" }}{{plugin "$GETCONTAINERID" .ID}}{{end}}{{end}}
EOF

cat /conf/myid.tmpl

cat > /conf/consul-template.conf <<EOF
consul = "$CONSUL_HOST:$CONSUL_PORT"


template {
  source = "/conf/myid.tmpl"
  destination = "/data/myid"
}

template {
  source = "/conf/zoo.cfg.tmpl"
  destination = "/conf/zoo.cfg"
}

exec {
  command = "${ZK_HOME}/bin/zkServer.sh start-foreground"
}

EOF

/bin/consul-template -config /conf/consul-template.conf
