version: '2'
services:
  web:
    image: alexinthesky/arachniwebui
    ports:
      - 9292:9292
  dispatcher:
    image: alexinthesky/arachnirpcd
    command: 
      - \'--nickname=$(hostname)\'
  dispatcher-worker:
    image: alexinthesky/arachnirpcd
    command: 
      - \'--nickname=$(hostname)\'
      - --neighbour=dispatcher:7331
