wordpress:
  image: alexinthesky/php7-fpm-wp-armhf
  volumes:
    - /wordpress_docroot/:/var/www/html/
  links:
    - db:mysql
  environment:
    WORDPRESS_DB_NAME: dbname
    WORDPRESS_DB_PASSWORD: dbpw
    WORDPRESS_DB_USER: dbuser
nginx:
  image: alexinthesky/nginx-wp-armhf
  links:
    - wordpress
  volumes_from:
    - wordpress
  environment:
    POST_MAX_SIZE: 128m
    VIRTUAL_HOST: wordpress.example.org
db:
  image: armbuilds/mariadb
  environment:
    MYSQL_DATABASE: dbname
    MYSQL_PASSWORD: dbpw
    MYSQL_ROOT_PASSWORD: example
    MYSQL_USER: dbuser
  volumes:
    - /folder_to_import_dump_from/:/docker-entrypoint-initdb.d/
